trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

steps:
  - script: |
      echo "✅ Hello from Azure DevOps!"
      echo "This pipeline is designed to always succeed."
      echo "Trigger time: $(Build.QueuedDate)"
    displayName: "Success step"
