trigger:
  branches:
    include:
      - main

pool:
  name: Default

steps:
  - script: |
      echo "✅ Hello from Azure DevOps!"
      echo "This pipeline is designed to always succeed."
      echo "Trigger time: $(Build.QueuedDate)"
    displayName: "Success step"
